name: Bundle a Roc library
description: Bundle and release a Roc library.

inputs:
  library-path:
    description: The path to the library's folder containing a `main.roc` file.
    required: true
    default: .
  roc-path:
    description: The absolute path to Roc. If this variable is not specified the action will try to find Roc using the `PATH` environment variable.
    required: true
    default: roc
  bundle-type:
    description: The filetype of the bundled library, either `.tar`, `.tar.gz` or `.tar.br`. Defaults to `.tar.br`.
    required: true
    default: .tar.br
  release:
    description: Whether or not the bundled library should be uploaded to the repository's releases. Defaults to only uploading when the action is triggered by a release event.
    required: true
    default: ${{ github.event_name == 'release' }}
  tag:
    description: The tag of the release to upload to. Defaults to the current event's name.
    default: ${{ github.ref }}
  token:
    description: A GitHub token.
    default: ${{ github.token }}

outputs:
  bundle-path:
    description: The absolute path to the bundled library.

runs:
  using: node16
  main: dist/index.js
